#!/bin/bash
# github_updater.sh - Poly-AI Framework GitHub Automation

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${BLUE}$1${NC}"
}

# Configuration
PROJECT_NAME="${1:-githubupdater-tools}"
GITHUB_USERNAME="${GITHUB_USER:-BoozeLee}"
GITHUB_ORG="${GITHUB_ORG:-Bakery-street-projct}"
REPO_NAME="${PROJECT_NAME}"

print_header "🚀 Poly-AI Framework GitHub Updater"
echo "Updating repository: $REPO_NAME"
echo "Organization: $GITHUB_ORG"
echo "User: $GITHUB_USERNAME"
echo ""

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    print_warning "Not in a git repository. Initializing..."
    git init
    git remote add origin "https://github.com/$GITHUB_ORG/$REPO_NAME.git"
    print_status "Git repository initialized"
fi

# Check if remote exists
if ! git remote get-url origin >/dev/null 2>&1; then
    print_status "Adding remote origin..."
    git remote add origin "https://github.com/$GITHUB_ORG/$REPO_NAME.git"
fi

# Check for uncommitted changes
if git diff --quiet && git diff --cached --quiet; then
    print_warning "No changes to commit"
    exit 0
fi

# Add all files
print_status "Adding files to git..."
git add .

# Create commit with timestamp and framework info
COMMIT_MSG="Poly-AI Framework Update: $(date '+%Y-%m-%d %H:%M:%S')

- Automated update via Poly-AI Framework
- Enhanced GitHub automation capabilities
- Improved workflow generation and deployment
- Advanced AI-powered tool discovery
- Enterprise-grade automation features

Generated by Poly-AI Framework v1.0"

git commit -m "$COMMIT_MSG"

# Push to GitHub
print_status "Pushing to GitHub..."
if git push -u origin main; then
    print_status "✅ Successfully pushed to GitHub!"
else
    print_error "Failed to push to GitHub"
    exit 1
fi

# Update framework metrics
print_status "Updating framework metrics..."
python3 -c "
from poly_framework import PolyAIFramework
import os

if os.getenv('GITHUB_TOKEN'):
    framework = PolyAIFramework()
    metrics = framework.get_metrics()
    print(f'Framework metrics updated: {metrics}')
else:
    print('GitHub token not set, skipping metrics update')
" 2>/dev/null || print_warning "Could not update metrics (GitHub token not set)"

print_header "🎉 GitHub update completed successfully!"
print_status "Repository: https://github.com/$GITHUB_ORG/$REPO_NAME"
print_status "Framework: Poly-AI Framework v1.0"